Project\OneBundle\Entity\Article:
    type: entity
    repositoryClass: Project\OneBundle\Repository\ArticleRepository
    table: article
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        text:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
    manyToOne:
        user:
            targetEntity: User
            cascade: [persist]
            inversedBy: articles
            joinColumn:
                name: user_id
                referencedColumnName: id
            orphanRemoval: true
    lifecycleCallbacks: {  }